In [1]:
# read csv
import csv
import os
import pandas as pd

# from "results" repository read all csv files
results_dir = "results"

all_csv = []
# for all csv file in results_dir or results_dir/subdir or results_dir/subdir/subdir
for root, dirs, files in os.walk(results_dir):
    for file in files:
        if file.endswith(".csv"):
            csv_file = os.path.join(root, file)
            all_csv.append(csv_file)
print(all_csv)

# create dictionary with all csv files
all_data = {}
for csv_file in all_csv:
    if os.path.isfile(f"{csv_file}"):
        data = pd.read_csv(f"{csv_file}")
        all_data[csv_file] = data

['results/Qwen-7B/checkpoint-1000_rosetta.csv', 'results/Qwen-7B/checkpoint-1500.csv', 'results/Qwen-7B/checkpoint-1500_rosetta.csv', 'results/Qwen-7B/checkpoint-500.csv', 'results/Qwen-7B/checkpoint-1000.csv', 'results/Qwen-7B/checkpoint-500_rosetta.csv', 'results/Qwen-7B_one_shot_length/checkpoint-1500.csv', 'results/Qwen-7B_one_shot_length/checkpoint-500.csv', 'results/Qwen-7B_one_shot_length/checkpoint-1000.csv', 'results/Qwen-3B/checkpoint-1000_rosetta.csv', 'results/Qwen-3B/checkpoint-1500.csv', 'results/Qwen-3B/checkpoint-1500_rosetta.csv', 'results/Qwen-3B/checkpoint-500.csv', 'results/Qwen-3B/checkpoint-1000.csv', 'results/Qwen-3B/checkpoint-500_rosetta.csv', 'results/Qwen-1.5B_one_shot/checkpoint-1000_rosetta.csv', 'results/Qwen-1.5B_one_shot/checkpoint-1500.csv', 'results/Qwen-1.5B_one_shot/checkpoint-1500_rosetta.csv', 'results/Qwen-1.5B_one_shot/checkpoint-500.csv', 'results/Qwen-1.5B_one_shot/checkpoint-1000.csv', 'results/Qwen-1.5B_one_shot/checkpoint-500_rosetta.csv', 'results/Base/zero_shot/7_rosetta.csv', 'results/Base/zero_shot/7.csv', 'results/Base/zero_shot/0.5_rosetta.csv', 'results/Base/zero_shot/0.5.csv', 'results/Base/zero_shot/1.5.csv', 'results/Base/zero_shot/1.5_rosetta.csv', 'results/Base/zero_shot/3_rosetta.csv', 'results/Base/zero_shot/3.csv', 'results/Base/one_shot/7_rosetta.csv', 'results/Base/one_shot/7.csv', 'results/Base/one_shot/0.5_rosetta.csv', 'results/Base/one_shot/0.5.csv', 'results/Base/one_shot/1.5.csv', 'results/Base/one_shot/1.5_rosetta.csv', 'results/Base/one_shot/3_rosetta.csv', 'results/Base/one_shot/3.csv', 'results/Base/five_shot/7_rosetta.csv', 'results/Base/five_shot/7.csv', 'results/Base/five_shot/0.5.csv', 'results/Base/five_shot/1.5.csv', 'results/Base/five_shot/1.5_rosetta.csv', 'results/Base/five_shot/3_rosetta.csv', 'results/Base/five_shot/3.csv', 'results/Qwen-7B_five_shot/checkpoint-1000_rosetta.csv', 'results/Qwen-7B_five_shot/checkpoint-1500.csv', 'results/Qwen-7B_five_shot/checkpoint-1500_rosetta.csv', 'results/Qwen-7B_five_shot/checkpoint-500.csv', 'results/Qwen-7B_five_shot/checkpoint-1000.csv', 'results/Qwen-7B_five_shot/checkpoint-500_rosetta.csv', 'results/Qwen-1.5B/checkpoint-1000_rosetta.csv', 'results/Qwen-1.5B/checkpoint-1500.csv', 'results/Qwen-1.5B/checkpoint-1500_rosetta.csv', 'results/Qwen-1.5B/checkpoint-500.csv', 'results/Qwen-1.5B/checkpoint-1000.csv', 'results/Qwen-1.5B/checkpoint-500_rosetta.csv', 'results/Qwen-7B_one_shot/checkpoint-1000_rosetta.csv', 'results/Qwen-7B_one_shot/checkpoint-1500.csv', 'results/Qwen-7B_one_shot/checkpoint-1500_rosetta.csv', 'results/Qwen-7B_one_shot/checkpoint-500.csv', 'results/Qwen-7B_one_shot/checkpoint-1000.csv', 'results/Qwen-7B_one_shot/checkpoint-500_rosetta.csv', 'results/Qwen-3B_one_shot/checkpoint-1000_rosetta.csv', 'results/Qwen-3B_one_shot/checkpoint-1500.csv', 'results/Qwen-3B_one_shot/checkpoint-1500_rosetta.csv', 'results/Qwen-3B_one_shot/checkpoint-500.csv', 'results/Qwen-3B_one_shot/checkpoint-1000.csv', 'results/Qwen-3B_one_shot/checkpoint-500_rosetta.csv', 'results/Qwen-0.5B/checkpoint-1000_rosetta.csv', 'results/Qwen-0.5B/checkpoint-1500.csv', 'results/Qwen-0.5B/checkpoint-1500_rosetta.csv', 'results/Qwen-0.5B/checkpoint-500.csv', 'results/Qwen-0.5B/checkpoint-1000.csv', 'results/Qwen-0.5B/checkpoint-500_rosetta.csv', 'results/Qwen-7B_length/checkpoint-1500.csv', 'results/Qwen-7B_length/checkpoint-500.csv', 'results/Qwen-7B_length/checkpoint-1000.csv', 'results/Qwen-0.5B_one_shot/checkpoint-1500.csv', 'results/Qwen-0.5B_one_shot/checkpoint-500.csv', 'results/Qwen-0.5B_one_shot/checkpoint-1000.csv', 'results/Qwen-7B_five_shot_length/checkpoint-1500.csv', 'results/Qwen-7B_five_shot_length/checkpoint-500.csv', 'results/Qwen-7B_five_shot_length/checkpoint-1000.csv']

In [2]:
# from all_data dictionary composed by name: data, create a table with the data calculating accuracy by counting rows with mean > 0
df = pd.DataFrame({"name": all_data.keys(),
                   "accuracy": [all_data[key]["match"].sum()/len(all_data[key]) for key in all_data.keys()],
                   "strict_accuracy": [(all_data[key]["sum"] == 4).sum()/len(all_data[key]) for key in all_data.keys()]
                   })
display(df)

,name,accuracy,strict_accuracy
0,results/Qwen-7B/checkpoint-1000_rosetta.csv,0.250000,0.200000
1,results/Qwen-7B/checkpoint-1500.csv,0.667930,0.570887
2,results/Qwen-7B/checkpoint-1500_rosetta.csv,0.250000,0.200000
3,results/Qwen-7B/checkpoint-500.csv,0.714177,0.520849
4,results/Qwen-7B/checkpoint-1000.csv,0.670963,0.572403
...,...,...,...
78,results/Qwen-0.5B_one_shot/checkpoint-500.csv,0.105383,0.029568
79,results/Qwen-0.5B_one_shot/checkpoint-1000.csv,0.126611,0.041698
80,results/Qwen-7B_five_shot_length/checkpoint-15...,0.788476,0.484458
81,results/Qwen-7B_five_shot_length/checkpoint-50...,0.728582,0.383624
82,results/Qwen-7B_five_shot_length/checkpoint-10...,0.781653,0.471569

#### Plots for Rosetta Code

In [9]:
import os
import pandas as pd

results_dir = "results"
all_csv = []
for root, dirs, files in os.walk(results_dir):
    for file in files:
        if file.endswith(".csv"):
            csv_file = os.path.join(root, file)
            all_csv.append(csv_file)
print(all_csv)

rows_to_remove = [6, 12, 13, 14, 18]
all_data = {}
for csv_file in all_csv:
    if "rosetta" in os.path.basename(csv_file).lower() and os.path.isfile(csv_file):
        data = pd.read_csv(csv_file)
        if len(data) > 0:
            filtered_data = data.drop(index=[i for i in rows_to_remove if i < len(data)])
            all_data[csv_file] = filtered_data

['results/Qwen-7B_one_shot_length/checkpoint-1000.csv', 'results/Qwen-7B_one_shot_length/checkpoint-1500.csv', 'results/Qwen-7B_one_shot_length/checkpoint-500.csv', 'results/Qwen-7B_length/checkpoint-1000.csv', 'results/Qwen-7B_length/checkpoint-1500.csv', 'results/Qwen-7B_length/checkpoint-500.csv', 'results/Qwen-3B_one_shot/checkpoint-1500_rosetta.csv', 'results/Qwen-3B_one_shot/checkpoint-500_rosetta.csv', 'results/Qwen-3B_one_shot/checkpoint-1000.csv', 'results/Qwen-3B_one_shot/checkpoint-1500.csv', 'results/Qwen-3B_one_shot/checkpoint-1000_rosetta.csv', 'results/Qwen-3B_one_shot/checkpoint-500.csv', 'results/Qwen-0.5B/checkpoint-1500_rosetta.csv', 'results/Qwen-0.5B/checkpoint-500_rosetta.csv', 'results/Qwen-0.5B/checkpoint-1000.csv', 'results/Qwen-0.5B/checkpoint-1500.csv', 'results/Qwen-0.5B/checkpoint-1000_rosetta.csv', 'results/Qwen-0.5B/checkpoint-500.csv', 'results/Base/zero_shot/7_rosetta.csv', 'results/Base/zero_shot/3.csv', 'results/Base/zero_shot/1.5_rosetta.csv', 'results/Base/zero_shot/7.csv', 'results/Base/zero_shot/0.5.csv', 'results/Base/zero_shot/0.5_rosetta.csv', 'results/Base/zero_shot/1.5.csv', 'results/Base/zero_shot/3_rosetta.csv', 'results/Base/five_shot/7_rosetta.csv', 'results/Base/five_shot/3.csv', 'results/Base/five_shot/1.5_rosetta.csv', 'results/Base/five_shot/7.csv', 'results/Base/five_shot/0.5.csv', 'results/Base/five_shot/0.5_rosetta.csv', 'results/Base/five_shot/1.5.csv', 'results/Base/five_shot/3_rosetta.csv', 'results/Base/one_shot/7_rosetta.csv', 'results/Base/one_shot/3.csv', 'results/Base/one_shot/1.5_rosetta.csv', 'results/Base/one_shot/7.csv', 'results/Base/one_shot/0.5.csv', 'results/Base/one_shot/0.5_rosetta.csv', 'results/Base/one_shot/1.5.csv', 'results/Base/one_shot/3_rosetta.csv', 'results/Qwen-0.5B_one_shot/checkpoint-1500_rosetta.csv', 'results/Qwen-0.5B_one_shot/checkpoint-500_rosetta.csv', 'results/Qwen-0.5B_one_shot/checkpoint-1000.csv', 'results/Qwen-0.5B_one_shot/checkpoint-1500.csv', 'results/Qwen-0.5B_one_shot/checkpoint-1000_rosetta.csv', 'results/Qwen-0.5B_one_shot/checkpoint-500.csv', 'results/Qwen-7B/checkpoint-1500_rosetta.csv', 'results/Qwen-7B/checkpoint-500_rosetta.csv', 'results/Qwen-7B/checkpoint-1000.csv', 'results/Qwen-7B/checkpoint-1500.csv', 'results/Qwen-7B/checkpoint-1000_rosetta.csv', 'results/Qwen-7B/checkpoint-500.csv', 'results/Qwen-1.5B_one_shot/checkpoint-1500_rosetta.csv', 'results/Qwen-1.5B_one_shot/checkpoint-500_rosetta.csv', 'results/Qwen-1.5B_one_shot/checkpoint-1000.csv', 'results/Qwen-1.5B_one_shot/checkpoint-1500.csv', 'results/Qwen-1.5B_one_shot/checkpoint-1000_rosetta.csv', 'results/Qwen-1.5B_one_shot/checkpoint-500.csv', 'results/Qwen-7B_five_shot/checkpoint-1500_rosetta.csv', 'results/Qwen-7B_five_shot/checkpoint-500_rosetta.csv', 'results/Qwen-7B_five_shot/checkpoint-1000.csv', 'results/Qwen-7B_five_shot/checkpoint-1500.csv', 'results/Qwen-7B_five_shot/checkpoint-1000_rosetta.csv', 'results/Qwen-7B_five_shot/checkpoint-500.csv', 'results/Qwen-3B/checkpoint-1500_rosetta.csv', 'results/Qwen-3B/checkpoint-500_rosetta.csv', 'results/Qwen-3B/checkpoint-1000.csv', 'results/Qwen-3B/checkpoint-1500.csv', 'results/Qwen-3B/checkpoint-1000_rosetta.csv', 'results/Qwen-3B/checkpoint-500.csv', 'results/Qwen-7B_five_shot_length/checkpoint-1000.csv', 'results/Qwen-7B_five_shot_length/checkpoint-1500.csv', 'results/Qwen-7B_five_shot_length/checkpoint-500.csv', 'results/Qwen-7B_one_shot/checkpoint-1500_rosetta.csv', 'results/Qwen-7B_one_shot/checkpoint-500_rosetta.csv', 'results/Qwen-7B_one_shot/checkpoint-1000.csv', 'results/Qwen-7B_one_shot/checkpoint-1500.csv', 'results/Qwen-7B_one_shot/checkpoint-1000_rosetta.csv', 'results/Qwen-7B_one_shot/checkpoint-500.csv', 'results/Qwen-1.5B/checkpoint-1500_rosetta.csv', 'results/Qwen-1.5B/checkpoint-500_rosetta.csv', 'results/Qwen-1.5B/checkpoint-1000.csv', 'results/Qwen-1.5B/checkpoint-1500.csv', 'results/Qwen-1.5B/checkpoint-1000_rosetta.csv', 'results/Qwen-1.5B/checkpoint-500.csv']

In [10]:
all_data

{'results/Qwen-3B_one_shot/checkpoint-1500_rosetta.csv':     match                                           question  sum  mean  \
 0    True  The Fibonacci sequence is a sequence Fn of nat...    3  0.75
 1   False  \nThe Sieve of Eratosthenes is a simple algori...    0  0.00
 2    True  \nSorting Algorithm\nThis is a sorting algorit...    3  0.75
 3   False  A binary search divides a range of values into...    0  0.00
 4   False  Greatest common divisor\nYou are encouraged to...    0  0.00
 5   False  Definitions\nThe factorial of 0 (zero) is defi...    0  0.00
 7   False  A palindrome is a phrase which reads the same ...    0  0.00
 8   False  The prime decomposition of a number is defined...    0  0.00
 9   False  Dijkstra's algorithm, conceived by Dutch compu...    0  0.00
 10  False  \nIn information theory and computer science, ...    0  0.00
 11  False  \nSolve the eight queens puzzle.\nYou can exte...    0  0.00
 15  False  \nSorting Algorithm\nThis is a sorting algorit...    0  0.00
 16  False  Task\nCreate a function that takes a Roman num...    0  0.00
 17  False  \nDefine a subsequence to be any output string...    0  0.00
 19  False  The 24 Game tests one's mental arithmetic.\nTa...    0  0.00

     match_1  match_2  match_3  match_4  \
 0         1        1        1        0
 1         0        0        0        0
 2         1        1        1        0
 3         0        0        0        0
 4         0        0        0        0
 5         0        0        0        0
 7         0        0        0        0
 8         0        0        0        0
 9         0        0        0        0
 10        0        0        0        0
 11        0        0        0        0
 15        0        0        0        0
 16        0        0        0        0
 17        0        0        0        0
 19        0        0        0        0

                                            gen_code_1  \
 0   <reasoning>\nTo generate the nth Fibonacci num...
 1   <reasoning>\nTo implement the Sieve of Eratost...
 2   <reasoning>\nTo implement the quicksort algori...
 3   <reasoning>\nTo implement a binary search algo...
 4   <reasoning>\nTo find the greatest common divis...
 5   <reasoning>\nTo solve this problem, we need to...
 7   <reasoning>\nTo determine if a given sequence ...
 8   <reasoning>\nTo solve this problem, we need to...
 9   <reasoning>\nTo implement Dijkstra's algorithm...
 10  <reasoning>\nTo implement the Levenshtein dist...
 11  <reasoning>\nTo solve the eight queens puzzle,...
 15  <reasoning>\nTo implement the merge sort algor...
 16  <reasoning>\nTo solve this problem, we need to...
 17  <reasoning>\nTo solve this problem, we need to...
 19  <reasoning>\nTo solve this problem, we need to...

                                            gen_code_2  \
 0   <reasoning>\nTo generate the nth Fibonacci num...
 1   <reasoning>\nTo implement the Sieve of Eratost...
 2   <reasoning>\nTo implement the quicksort algori...
 3   <reasoning>\nTo implement a binary search algo...
 4   <reasoning>\nTo find the greatest common divis...
 5   <reasoning>\nTo solve this problem, we need to...
 7   <reasoning>\nTo determine if a given sequence ...
 8   <reasoning>\nTo solve this problem, we need to...
 9   <reasoning>\nTo implement Dijkstra's algorithm...
 10  <reasoning>\nTo implement the Levenshtein dist...
 11  <reasoning>\nTo solve the eight queens puzzle,...
 15  <reasoning>\nTo implement the merge sort algor...
 16  <reasoning>\nTo create a function that convert...
 17  <reasoning>\nTo solve this problem, we need to...
 19  <reasoning>\nTo solve this problem, we need to...

                                            gen_code_3  \
 0   <reasoning>\nTo generate the nth Fibonacci num...
 1   <reasoning>\nTo implement the Sieve of Eratost...
 2   <reasoning>\nTo implement the quicksort algori...
 3   <reasoning>\nTo implement a binary search algo...
 4   <reasoning>\nTo find the greatest common divis...
 5   <reasoning>\nTo solve this problem, we need to...
 7   <reasoning>\nTo determine if a given sequence ...
 8   <reasoning>\nTo solve this problem, we need to...
 9   <reasoning>\nTo implement Dijkstra's algorithm...
 10  <reasoning>\nTo implement the Levenshtein dist...
 11  <reasoning>\nTo solve the eight queens puzzle,...
 15  <reasoning>\nTo implement the merge sort algor...
 16  <reasoning>\nTo create a function that convert...
 17  <reasoning>\nTo solve this problem, we need to...
 19  <reasoning>\nTo solve this problem, we need to...

                                            gen_code_4
 0   <reasoning>\nTo generate the nth Fibonacci num...
 1   <reasoning>\nTo implement the Sieve of Eratost...
 2   <reasoning>\nTo implement the quicksort algori...
 3   <reasoning>\nTo implement a binary search algo...
 4   <reasoning>\nTo find the greatest common divis...
 5   <reasoning>\nTo solve this problem, we need to...
 7   <reasoning>\nTo determine if a given sequence ...
 8   <reasoning>\nTo solve this problem, we need to...
 9   <reasoning>\nTo implement Dijkstra's algorithm...
 10  <reasoning>\nTo implement the Levenshtein dist...
 11  <reasoning>\nTo solve the eight queens puzzle,...
 15  <reasoning>\nTo implement the merge sort algor...
 16  <reasoning>\nTo create a function that convert...
 17  <reasoning>\nTo solve this problem, we need to...
 19  <reasoning>\nTo solve this problem, we need to...  ,
 'results/Qwen-3B_one_shot/checkpoint-500_rosetta.csv':     match                                           question  sum  mean  \
 0    True  The Fibonacci sequence is a sequence Fn of nat...    2  0.50
 1   False  \nThe Sieve of Eratosthenes is a simple algori...    0  0.00
 2    True  \nSorting Algorithm\nThis is a sorting algorit...    4  1.00
 3   False  A binary search divides a range of values into...    0  0.00
 4   False  Greatest common divisor\nYou are encouraged to...    0  0.00
 5    True  Definitions\nThe factorial of 0 (zero) is defi...    3  0.75
 7   False  A palindrome is a phrase which reads the same ...    0  0.00
 8   False  The prime decomposition of a number is defined...    0  0.00
 9   False  Dijkstra's algorithm, conceived by Dutch compu...    0  0.00
 10  False  \nIn information theory and computer science, ...    0  0.00
 11  False  \nSolve the eight queens puzzle.\nYou can exte...    0  0.00
 15  False  \nSorting Algorithm\nThis is a sorting algorit...    0  0.00
 16  False  Task\nCreate a function that takes a Roman num...    0  0.00
 17  False  \nDefine a subsequence to be any output string...    0  0.00
 19  False  The 24 Game tests one's mental arithmetic.\nTa...    0  0.00

     match_1  match_2  match_3  match_4  \
 0         0        1        0        1
 1         0        0        0        0
 2         1        1        1        1
 3         0        0        0        0
 4         0        0        0        0
 5         1        1        0        1
 7         0        0        0        0
 8         0        0        0        0
 9         0        0        0        0
 10        0        0        0        0
 11        0        0        0        0
 15        0        0        0        0
 16        0        0        0        0
 17        0        0        0        0
 19        0        0        0        0

                                            gen_code_1  \
 0   <reasoning>\nTo generate the nth Fibonacci num...
 1   <reasoning>\nThe Sieve of Eratosthenes is an e...
 2   <reasoning>\nHere you are reasoning about the ...
 3   <reasoning>\nTo implement a binary search algo...
 4   <reasoning>\nTo find the greatest common divis...
 5   <reasoning>\nTo solve this problem, we need to...
 7   <reasoning>\nTo determine if a given sequence ...
 8   <reasoning>\nTo solve this problem, we need to...
 9   <reasoning>\nTo implement Dijkstra's algorithm...
 10  <reasoning>\nTo implement the Levenshtein dist...
 11  <reasoning>\nTo solve the eight queens puzzle,...
 15  <reasoning>\nTo implement the merge sort algor...
 16  <reasoning>\nTo create a function that convert...
 17  <reasoning>\nTo solve this problem, we need to...
 19  <reasoning>\nTo solve this problem, we need to...

                                            gen_code_2  \
 0   <reasoning>\nTo generate the nth Fibonacci num...
 1   <reasoning>\nThe Sieve of Eratosthenes is an e...
 2   <reasoning>\nTo implement the quicksort algori...
 3   <reasoning>\nTo implement a binary search algo...
 4   <reasoning>\nTo find the greatest common divis...
 5   <reasoning>\nTo solve this problem, we need to...
 7   <reasoning>\nTo determine if a given sequence ...
 8   <reasoning>\nTo solve this problem, we need to...
 9   <reasoning>\nTo implement Dijkstra's algorithm...
 10  <reasoning>\nTo implement the Levenshtein dist...
 11  <reasoning>\nThe eight queens puzzle is a clas...
 15  <reasoning>\nTo implement the merge sort algor...
 16  <reasoning>\nTo create a function that convert...
 17  <reasoning>\nTo solve this problem, we need to...
 19  <reasoning>\nTo solve this problem, we need to...

                                            gen_code_3  \
 0   <reasoning>\nTo generate the nth Fibonacci num...
 1   <reasoning>\nTo implement the Sieve of Eratost...
 2   <reasoning>\nTo implement the quicksort algori...
 3   <reasoning>\nTo implement a binary search algo...
 4   <reasoning>\nTo find the greatest common divis...
 5   <reasoning>\nTo solve this problem, we need to...
 7   <reasoning>\nTo determine if a given sequence ...
 8   <reasoning>\nTo solve this problem, we need to...
 9   <reasoning>\nTo implement Dijkstra's algorithm...
 10  <reasoning>\nTo implement the Levenshtein dist...
 11  <reasoning>\nTo solve the eight queens puzzle,...
 15  <reasoning>\nTo implement the merge sort algor...
 16  <reasoning>\nTo create a function that convert...
 17  <reasoning>\nTo solve this problem, we need to...
 19  <reasoning>\nTo solve this problem, we need to...

                                            gen_code_4
 0   <reasoning>\nTo generate the nth Fibonacci num...
 1   <reasoning>\nThe Sieve of Eratosthenes is an e...
 2   <reasoning>\nTo implement the quicksort algori...
 3   <reasoning>\nTo implement a binary search algo...
 4   <reasoning>\nTo find the greatest common divis...
 5   <reasoning>\nTo solve this problem, we need to...
 7   <reasoning>\nTo determine if a given sequence ...
 8   <reasoning>\nTo solve this problem, we need to...
 9   <reasoning>\nTo implement Dijkstra's algorithm...
 10  <reasoning>\nTo implement the Levenshtein dist...
 11  <reasoning>\nThe eight queens puzzle is a clas...
 15  <reasoning>\nTo implement the merge sort algor...
 16  <reasoning>\nTo create a function that convert...
 17  <reasoning>\nTo solve this problem, we need to...
 19  <reasoning>\nTo solve this problem, we need to...  ,
 'results/Qwen-3B_one_shot/checkpoint-1000_rosetta.csv':     match                                           question  sum  mean  \
 0    True  The Fibonacci sequence is a sequence Fn of nat...    3  0.75
 1   False  \nThe Sieve of Eratosthenes is a simple algori...    0  0.00
 2    True  \nSorting Algorithm\nThis is a sorting algorit...    2  0.50
 3   False  A binary search divides a range of values into...    0  0.00
 4   False  Greatest common divisor\nYou are encouraged to...    0  0.00
 5   False  Definitions\nThe factorial of 0 (zero) is defi...    0  0.00
 7   False  A palindrome is a phrase which reads the same ...    0  0.00
 8   False  The prime decomposition of a number is defined...    0  0.00
 9   False  Dijkstra's algorithm, conceived by Dutch compu...    0  0.00
 10  False  \nIn information theory and computer science, ...    0  0.00
 11  False  \nSolve the eight queens puzzle.\nYou can exte...    0  0.00
 15  False  \nSorting Algorithm\nThis is a sorting algorit...    0  0.00
 16  False  Task\nCreate a function that takes a Roman num...    0  0.00
 17  False  \nDefine a subsequence to be any output string...    0  0.00
 19  False  The 24 Game tests one's mental arithmetic.\nTa...    0  0.00

     match_1  match_2  match_3  match_4  \
 0         1        1        1        0
 1         0        0        0        0
 2         1        0        1        0
 3         0        0        0        0
 4         0        0        0        0
 5         0        0        0        0
 7         0        0        0        0
 8         0        0        0        0
 9         0        0        0        0
 10        0        0        0        0
 11        0        0        0        0
 15        0        0        0        0
 16        0        0        0        0
 17        0        0        0        0
 19        0        0        0        0

                                            gen_code_1  \
 0   <reasoning>\nTo generate the nth Fibonacci num...
 1   <reasoning>\nTo implement the Sieve of Eratost...
 2   <reasoning>\nTo implement the quicksort algori...
 3   <reasoning>\nTo implement a binary search algo...
 4   <reasoning>\nTo find the greatest common divis...
 5   <reasoning>\nTo solve this problem, we need to...
 7   <reasoning>\nTo determine if a given sequence ...
 8   <reasoning>\nTo solve this problem, we need to...
 9   <reasoning>\nTo implement Dijkstra's algorithm...
 10  <reasoning>\nTo implement the Levenshtein dist...
 11  <reasoning>\nTo solve the eight queens puzzle,...
 15  <reasoning>\nTo implement the merge sort algor...
 16  <reasoning>\nTo create a function that convert...
 17  <reasoning>\nTo solve this problem, we need to...
 19  <reasoning>\nTo solve this problem, we need to...

                                            gen_code_2  \
 0   <reasoning>\nTo generate the nth Fibonacci num...
 1   <reasoning>\nTo implement the Sieve of Eratost...
 2   <reasoning>\nTo implement the quicksort algori...
 3   <reasoning>\nTo implement a binary search algo...
 4   <reasoning>\nTo find the greatest common divis...
 5   <reasoning>\nTo solve this problem, we need to...
 7   <reasoning>\nTo determine if a given sequence ...
 8   <reasoning>\nTo solve this problem, we need to...
 9   <reasoning>\nTo implement Dijkstra's algorithm...
 10  <reasoning>\nTo implement the Levenshtein dist...
 11  <reasoning>\nTo solve the eight queens puzzle,...
 15  <reasoning>\nTo implement the merge sort algor...
 16  <reasoning>\nTo create a function that convert...
 17  <reasoning>\nTo solve this problem, we need to...
 19  <reasoning>\nTo solve this problem, we need to...

                                            gen_code_3  \
 0   <reasoning>\nTo generate the nth Fibonacci num...
 1   <reasoning>\nTo implement the Sieve of Eratost...
 2   <reasoning>\nTo implement the quicksort algori...
 3   <reasoning>\nTo implement a binary search algo...
 4   <reasoning>\nTo find the greatest common divis...
 5   <reasoning>\nTo solve this problem, we need to...
 7   <reasoning>\nTo determine if a given sequence ...
 8   <reasoning>\nTo solve this problem, we need to...
 9   <reasoning>\nTo implement Dijkstra's algorithm...
 10  <reasoning>\nTo implement the Levenshtein dist...
 11  <reasoning>\nTo solve the eight queens puzzle,...
 15  <reasoning>\nTo implement the merge sort algor...
 16  <reasoning>\nTo create a function that convert...
 17  <reasoning>\nTo solve this problem, we need to...
 19  <reasoning>\nTo solve this problem, we need to...

                                            gen_code_4
 0   <reasoning>\nTo generate the nth Fibonacci num...
 1   <reasoning>\nTo implement the Sieve of Eratost...
 2   <reasoning>\nTo implement the quicksort algori...
 3   <reasoning>\nTo implement a binary search algo...
 4   <reasoning>\nTo find the greatest common divis...
 5   <reasoning>\nTo solve this problem, we need to...
 7   <reasoning>\nTo determine if a given sequence ...
 8   <reasoning>\nTo solve this problem, we need to...
 9   <reasoning>\nTo implement Dijkstra's algorithm...
 10  <reasoning>\nTo implement the Levenshtein dist...
 11  <reasoning>\nTo solve the eight queens puzzle,...
 15  <reasoning>\nTo implement the merge sort algor...
 16  <reasoning>\nTo create a function that convert...
 17  <reasoning>\nTo solve this problem, we need to...
 19  <reasoning>\nTo solve this problem, we need to...  ,
 'results/Qwen-0.5B/checkpoint-1500_rosetta.csv':     match                                           question  sum  mean  \
 0   False  The Fibonacci sequence is a sequence Fn of nat...    0   0.0
 1   False  \nThe Sieve of Eratosthenes is a simple algori...    0   0.0
 2   False  \nSorting Algorithm\nThis is a sorting algorit...    0   0.0
 3   False  A binary search divides a range of values into...    0   0.0
 4   False  Greatest common divisor\nYou are encouraged to...    0   0.0
 5   False  Definitions\nThe factorial of 0 (zero) is defi...    0   0.0
 7   False  A palindrome is a phrase which reads the same ...    0   0.0
 8   False  The prime decomposition of a number is defined...    0   0.0
 9   False  Dijkstra's algorithm, conceived by Dutch compu...    0   0.0
 10  False  \nIn information theory and computer science, ...    0   0.0
 11  False  \nSolve the eight queens puzzle.\nYou can exte...    0   0.0
 15   True  \nSorting Algorithm\nThis is a sorting algorit...    2   0.5
 16  False  Task\nCreate a function that takes a Roman num...    0   0.0
 17  False  \nDefine a subsequence to be any output string...    0   0.0
 19  False  The 24 Game tests one's mental arithmetic.\nTa...    0   0.0

     match_1  match_2  match_3  match_4  \
 0         0        0        0        0
 1         0        0        0        0
 2         0        0        0        0
 3         0        0        0        0
 4         0        0        0        0
 5         0        0        0        0
 7         0        0        0        0
 8         0        0        0        0
 9         0        0        0        0
 10        0        0        0        0
 11        0        0        0        0
 15        1        1        0        0
 16        0        0        0        0
 17        0        0        0        0
 19        0        0        0        0

                                            gen_code_1  \
 0   <reasoning>\nThe Fibonacci sequence is defined...
 1   <reasoning>\nThe Sieve of Eratosthenes algorit...
 2   <reasoning>\nThe given instruction is to imple...
 3   <reasoning>\nBinary search is a divide and con...
 4   <reasoning>\nThe task is to find the greatest ...
 5   <reasoning>\nThe factorial function is defined...
 7   <reasoning>\nA palindrome is a sequence of cha...
 8   <reasoning>\nThe task is to find the prime dec...
 9   <reasoning>\nDijkstra's algorithm is a graph s...
 10  <reasoning>\nThe Levenshtein distance between ...
 11  <reasoning>\nThe eight queens puzzle is a clas...
 15  <reasoning>\nThe merge sort algorithm is a rec...
 16  <reasoning>\nThe Roman numeral "mcmxc" is a va...
 17  <reasoning>\nThe task is to find the longest c...
 19  <reasoning>\nThe task requires the program to ...

                                            gen_code_2  \
 0   <reasoning>\nThe Fibonacci sequence is defined...
 1   <reasoning>\nThe Sieve of Eratosthenes algorit...
 2   <reasoning>\nThe given instruction is about so...
 3   <reasoning>\nBinary search is a divide and con...
 4   <reasoning>\nThe task is to find the greatest ...
 5   <reasoning>\nThe factorial function is defined...
 7   <reasoning>\nA palindrome is a sequence of cha...
 8   <reasoning>\nThe task is to find the prime dec...
 9   <reasoning>\nDijkstra's algorithm is a graph s...
 10  <reasoning>\nThe Levenshtein distance between ...
 11  <reasoning>\nThe eight queens puzzle is a clas...
 15  <reasoning>\nThe merge sort algorithm is a rec...
 16  <reasoning>\nThe Roman numeral "mcmxc" is a va...
 17  <reasoning>\nThe task is to find the longest c...
 19  <reasoning>\nThe task requires generating a ra...

                                            gen_code_3  \
 0   <reasoning>\nThe Fibonacci sequence is defined...

In [11]:
df = pd.DataFrame({
    "name": all_data.keys(),
    "accuracy": [all_data[key]["match"].sum()/len(all_data[key]) for key in all_data.keys()],
    "strict_accuracy": [(all_data[key]["sum"] == 4).sum()/len(all_data[key]) for key in all_data.keys()]
})
display(df)

,name,accuracy,strict_accuracy
0,results/Qwen-3B_one_shot/checkpoint-1500_roset...,0.133333,0.000000
1,results/Qwen-3B_one_shot/checkpoint-500_rosett...,0.200000,0.066667
2,results/Qwen-3B_one_shot/checkpoint-1000_roset...,0.133333,0.000000
3,results/Qwen-0.5B/checkpoint-1500_rosetta.csv,0.066667,0.000000
4,results/Qwen-0.5B/checkpoint-500_rosetta.csv,0.066667,0.066667
5,results/Qwen-0.5B/checkpoint-1000_rosetta.csv,0.066667,0.000000
6,results/Base/zero_shot/7_rosetta.csv,0.266667,0.133333
7,results/Base/zero_shot/1.5_rosetta.csv,0.000000,0.000000
8,results/Base/zero_shot/0.5_rosetta.csv,0.000000,0.000000
9,results/Base/zero_shot/3_rosetta.csv,0.200000,0.066667
10,results/Base/five_shot/7_rosetta.csv,0.400000,0.266667
11,results/Base/five_shot/1.5_rosetta.csv,0.000000,0.000000
12,results/Base/five_shot/0.5_rosetta.csv,0.000000,0.000000
13,results/Base/five_shot/3_rosetta.csv,0.200000,0.000000
14,results/Base/one_shot/7_rosetta.csv,0.266667,0.200000
15,results/Base/one_shot/1.5_rosetta.csv,0.133333,0.000000
16,results/Base/one_shot/0.5_rosetta.csv,0.000000,0.000000
17,results/Base/one_shot/3_rosetta.csv,0.066667,0.000000
18,results/Qwen-0.5B_one_shot/checkpoint-1500_ros...,0.133333,0.000000
19,results/Qwen-0.5B_one_shot/checkpoint-500_rose...,0.133333,0.000000
20,results/Qwen-0.5B_one_shot/checkpoint-1000_ros...,0.133333,0.066667
21,results/Qwen-7B/checkpoint-1500_rosetta.csv,0.333333,0.266667
22,results/Qwen-7B/checkpoint-500_rosetta.csv,0.266667,0.266667
23,results/Qwen-7B/checkpoint-1000_rosetta.csv,0.333333,0.266667
24,results/Qwen-1.5B_one_shot/checkpoint-1500_ros...,0.200000,0.000000
25,results/Qwen-1.5B_one_shot/checkpoint-500_rose...,0.066667,0.000000
26,results/Qwen-1.5B_one_shot/checkpoint-1000_ros...,0.066667,0.000000
27,results/Qwen-7B_five_shot/checkpoint-1500_rose...,0.333333,0.133333
28,results/Qwen-7B_five_shot/checkpoint-500_roset...,0.400000,0.200000
29,results/Qwen-7B_five_shot/checkpoint-1000_rose...,0.400000,0.200000
30,results/Qwen-3B/checkpoint-1500_rosetta.csv,0.133333,0.133333
31,results/Qwen-3B/checkpoint-500_rosetta.csv,0.133333,0.066667
32,results/Qwen-3B/checkpoint-1000_rosetta.csv,0.200000,0.066667
33,results/Qwen-7B_one_shot/checkpoint-1500_roset...,0.333333,0.266667
34,results/Qwen-7B_one_shot/checkpoint-500_rosett...,0.466667,0.333333
35,results/Qwen-7B_one_shot/checkpoint-1000_roset...,0.333333,0.266667
36,results/Qwen-1.5B/checkpoint-1500_rosetta.csv,0.133333,0.066667
37,results/Qwen-1.5B/checkpoint-500_rosetta.csv,0.200000,0.000000
38,results/Qwen-1.5B/checkpoint-1000_rosetta.csv,0.133333,0.066667