In [13]:
# read csv
import csv
import os
import pandas as pd

# from "results" repository read all csv files
results_dir = "results"

all_csv = []
# for all csv file in results_dir or results_dir/subdir or results_dir/subdir/subdir
for root, dirs, files in os.walk(results_dir):
    for file in files:
        if file.endswith(".csv"):
            csv_file = os.path.join(root, file)
            all_csv.append(csv_file)
all_csv = [csv_file for csv_file in all_csv if "gsm_symbolic" in csv_file and "results.csv" not in csv_file and "one_shot" in csv_file and
"p1" in csv_file]
print(all_csv)

# create dictionary with all csv files
all_data = {}
for csv_file in all_csv:
    if os.path.isfile(f"{csv_file}"):
        data = pd.read_csv(f"{csv_file}")
        all_data[csv_file] = data

['results/Qwen-7B_one_shot_length/checkpoint-500_gsm_symbolic_p1.csv', 'results/Qwen-7B_one_shot_length/checkpoint-1000_gsm_symbolic_p1.csv', 'results/Qwen-7B_one_shot_length/checkpoint-1500_gsm_symbolic_p1.csv', 'results/Base/one_shot/7_gsm_symbolic_p1.csv', 'results/Qwen-7B_one_shot_length_plus/checkpoint-500_gsm_symbolic_p1.csv', 'results/Qwen-7B_one_shot_length_plus/checkpoint-1000_gsm_symbolic_p1.csv', 'results/Qwen-7B_one_shot_length_plus/checkpoint-1500_gsm_symbolic_p1.csv', 'results/Qwen-7B_one_shot/checkpoint-500_gsm_symbolic_p1.csv', 'results/Qwen-7B_one_shot/checkpoint-1000_gsm_symbolic_p1.csv', 'results/Qwen-7B_one_shot/checkpoint-1500_gsm_symbolic_p1.csv']

In [14]:
# from all_data dictionary composed by name: data, create a table with the data calculating accuracy by counting rows with mean > 0
df = pd.DataFrame({"name": all_data.keys(),
                   "accuracy": [all_data[key]["match"].sum()/len(all_data[key]) for key in all_data.keys()],
                   "strict_accuracy": [(all_data[key]["sum"] == 4).sum()/len(all_data[key]) for key in all_data.keys()]
                   })
display(df)

# save the table to csv
df.to_csv("results/results.csv", index=False)

,name,accuracy,strict_accuracy
0,results/Qwen-7B_one_shot_length/checkpoint-500...,0.746923,0.398462
1,results/Qwen-7B_one_shot_length/checkpoint-100...,0.782308,0.442308
2,results/Qwen-7B_one_shot_length/checkpoint-150...,0.786923,0.444615
3,results/Base/one_shot/7_gsm_symbolic_p1.csv,0.753846,0.376154
4,results/Qwen-7B_one_shot_length_plus/checkpoin...,0.770000,0.479231
5,results/Qwen-7B_one_shot_length_plus/checkpoin...,0.792308,0.563077
6,results/Qwen-7B_one_shot_length_plus/checkpoin...,0.803077,0.574615
7,results/Qwen-7B_one_shot/checkpoint-500_gsm_sy...,0.578462,0.454615
8,results/Qwen-7B_one_shot/checkpoint-1000_gsm_s...,0.479231,0.353077
9,results/Qwen-7B_one_shot/checkpoint-1500_gsm_s...,0.470000,0.344615

#### Plots for Rosetta Code

In [4]:
import os
import pandas as pd

results_dir = "results"
all_csv = []
for root, dirs, files in os.walk(results_dir):
    for file in files:
        if file.endswith(".csv"):
            csv_file = os.path.join(root, file)
            all_csv.append(csv_file)
print(all_csv)

rows_to_remove = [6, 12, 13, 14, 18]
all_data = {}
for csv_file in all_csv:
    if "rosetta2" in os.path.basename(csv_file).lower() and os.path.isfile(csv_file):
        data = pd.read_csv(csv_file)
        if len(data) > 0:
            filtered_data = data.drop(index=[i for i in rows_to_remove if i < len(data)])
            all_data[csv_file] = filtered_data

['results/results.csv', 'results/Qwen-7B/checkpoint-1000_rosetta.csv', 'results/Qwen-7B/checkpoint-1500.csv', 'results/Qwen-7B/checkpoint-500_rosetta2.csv', 'results/Qwen-7B/checkpoint-1500_rosetta.csv', 'results/Qwen-7B/checkpoint-1000_rosetta2.csv', 'results/Qwen-7B/checkpoint-500.csv', 'results/Qwen-7B/checkpoint-1000.csv', 'results/Qwen-7B/checkpoint-1500_rosetta2.csv', 'results/Qwen-7B/checkpoint-500_rosetta.csv', 'results/Qwen-7B_one_shot_length/checkpoint-1500.csv', 'results/Qwen-7B_one_shot_length/checkpoint-500.csv', 'results/Qwen-7B_one_shot_length/checkpoint-1000.csv', 'results/Qwen-3B/checkpoint-1000_rosetta.csv', 'results/Qwen-3B/checkpoint-1500.csv', 'results/Qwen-3B/checkpoint-500_rosetta2.csv', 'results/Qwen-3B/checkpoint-1500_rosetta.csv', 'results/Qwen-3B/checkpoint-1000_rosetta2.csv', 'results/Qwen-3B/checkpoint-500.csv', 'results/Qwen-3B/checkpoint-1000.csv', 'results/Qwen-3B/checkpoint-1500_rosetta2.csv', 'results/Qwen-3B/checkpoint-500_rosetta.csv', 'results/Qwen-1.5B_one_shot/checkpoint-1000_rosetta.csv', 'results/Qwen-1.5B_one_shot/checkpoint-1500.csv', 'results/Qwen-1.5B_one_shot/checkpoint-500_rosetta2.csv', 'results/Qwen-1.5B_one_shot/checkpoint-1500_rosetta.csv', 'results/Qwen-1.5B_one_shot/checkpoint-1000_rosetta2.csv', 'results/Qwen-1.5B_one_shot/checkpoint-500.csv', 'results/Qwen-1.5B_one_shot/checkpoint-1000.csv', 'results/Qwen-1.5B_one_shot/checkpoint-1500_rosetta2.csv', 'results/Qwen-1.5B_one_shot/checkpoint-500_rosetta.csv', 'results/Base/zero_shot/0.5_rosetta2.csv', 'results/Base/zero_shot/7_rosetta.csv', 'results/Base/zero_shot/7_rosetta2.csv', 'results/Base/zero_shot/7.csv', 'results/Base/zero_shot/0.5_rosetta.csv', 'results/Base/zero_shot/0.5.csv', 'results/Base/zero_shot/3_rosetta2.csv', 'results/Base/zero_shot/1.5.csv', 'results/Base/zero_shot/1.5_rosetta.csv', 'results/Base/zero_shot/3_rosetta.csv', 'results/Base/zero_shot/1.5_rosetta2.csv', 'results/Base/zero_shot/3.csv', 'results/Base/one_shot/0.5_rosetta2.csv', 'results/Base/one_shot/7_rosetta.csv', 'results/Base/one_shot/7_rosetta2.csv', 'results/Base/one_shot/7.csv', 'results/Base/one_shot/0.5_rosetta.csv', 'results/Base/one_shot/0.5.csv', 'results/Base/one_shot/3_rosetta2.csv', 'results/Base/one_shot/1.5.csv', 'results/Base/one_shot/1.5_rosetta.csv', 'results/Base/one_shot/3_rosetta.csv', 'results/Base/one_shot/1.5_rosetta2.csv', 'results/Base/one_shot/3.csv', 'results/Base/five_shot/0.5_rosetta2.csv', 'results/Base/five_shot/7_rosetta.csv', 'results/Base/five_shot/7_rosetta2.csv', 'results/Base/five_shot/7.csv', 'results/Base/five_shot/0.5_rosetta.csv', 'results/Base/five_shot/0.5.csv', 'results/Base/five_shot/3_rosetta2.csv', 'results/Base/five_shot/1.5.csv', 'results/Base/five_shot/1.5_rosetta.csv', 'results/Base/five_shot/3_rosetta.csv', 'results/Base/five_shot/1.5_rosetta2.csv', 'results/Base/five_shot/3.csv', 'results/Qwen-7B_five_shot/checkpoint-1000_rosetta.csv', 'results/Qwen-7B_five_shot/checkpoint-1500.csv', 'results/Qwen-7B_five_shot/checkpoint-500_rosetta2.csv', 'results/Qwen-7B_five_shot/checkpoint-1500_rosetta.csv', 'results/Qwen-7B_five_shot/checkpoint-1000_rosetta2.csv', 'results/Qwen-7B_five_shot/checkpoint-500.csv', 'results/Qwen-7B_five_shot/checkpoint-1000.csv', 'results/Qwen-7B_five_shot/checkpoint-1500_rosetta2.csv', 'results/Qwen-7B_five_shot/checkpoint-500_rosetta.csv', 'results/Qwen-1.5B/checkpoint-1000_rosetta.csv', 'results/Qwen-1.5B/checkpoint-1500.csv', 'results/Qwen-1.5B/checkpoint-500_rosetta2.csv', 'results/Qwen-1.5B/checkpoint-1500_rosetta.csv', 'results/Qwen-1.5B/checkpoint-1000_rosetta2.csv', 'results/Qwen-1.5B/checkpoint-500.csv', 'results/Qwen-1.5B/checkpoint-1000.csv', 'results/Qwen-1.5B/checkpoint-1500_rosetta2.csv', 'results/Qwen-1.5B/checkpoint-500_rosetta.csv', 'results/Qwen-7B_one_shot/checkpoint-1000_rosetta.csv', 'results/Qwen-7B_one_shot/checkpoint-1500.csv', 'results/Qwen-7B_one_shot/checkpoint-500_rosetta2.csv', 'results/Qwen-7B_one_shot/checkpoint-1500_rosetta.csv', 'results/Qwen-7B_one_shot/checkpoint-1000_rosetta2.csv', 'results/Qwen-7B_one_shot/checkpoint-500.csv', 'results/Qwen-7B_one_shot/checkpoint-1000.csv', 'results/Qwen-7B_one_shot/checkpoint-1500_rosetta2.csv', 'results/Qwen-7B_one_shot/checkpoint-500_rosetta.csv', 'results/Qwen-3B_one_shot/checkpoint-1000_rosetta.csv', 'results/Qwen-3B_one_shot/checkpoint-1500.csv', 'results/Qwen-3B_one_shot/checkpoint-500_rosetta2.csv', 'results/Qwen-3B_one_shot/checkpoint-1500_rosetta.csv', 'results/Qwen-3B_one_shot/checkpoint-1000_rosetta2.csv', 'results/Qwen-3B_one_shot/checkpoint-500.csv', 'results/Qwen-3B_one_shot/checkpoint-1000.csv', 'results/Qwen-3B_one_shot/checkpoint-1500_rosetta2.csv', 'results/Qwen-3B_one_shot/checkpoint-500_rosetta.csv', 'results/Qwen-0.5B/checkpoint-1000_rosetta.csv', 'results/Qwen-0.5B/checkpoint-1500.csv', 'results/Qwen-0.5B/checkpoint-500_rosetta2.csv', 'results/Qwen-0.5B/checkpoint-1500_rosetta.csv', 'results/Qwen-0.5B/checkpoint-1000_rosetta2.csv', 'results/Qwen-0.5B/checkpoint-500.csv', 'results/Qwen-0.5B/checkpoint-1000.csv', 'results/Qwen-0.5B/checkpoint-1500_rosetta2.csv', 'results/Qwen-0.5B/checkpoint-500_rosetta.csv', 'results/Qwen-7B_length/checkpoint-1500.csv', 'results/Qwen-7B_length/checkpoint-500.csv', 'results/Qwen-7B_length/checkpoint-1000.csv', 'results/Qwen-0.5B_one_shot/checkpoint-1000_rosetta.csv', 'results/Qwen-0.5B_one_shot/checkpoint-1500.csv', 'results/Qwen-0.5B_one_shot/checkpoint-500_rosetta2.csv', 'results/Qwen-0.5B_one_shot/checkpoint-1500_rosetta.csv', 'results/Qwen-0.5B_one_shot/checkpoint-1000_rosetta2.csv', 'results/Qwen-0.5B_one_shot/checkpoint-500.csv', 'results/Qwen-0.5B_one_shot/checkpoint-1000.csv', 'results/Qwen-0.5B_one_shot/checkpoint-1500_rosetta2.csv', 'results/Qwen-0.5B_one_shot/checkpoint-500_rosetta.csv', 'results/Qwen-7B_length_plus/checkpoint-1500.csv', 'results/Qwen-7B_length_plus/checkpoint-500.csv', 'results/Qwen-7B_length_plus/checkpoint-1000.csv', 'results/Qwen-7B_five_shot_length/checkpoint-1500.csv', 'results/Qwen-7B_five_shot_length/checkpoint-500.csv', 'results/Qwen-7B_five_shot_length/checkpoint-1000.csv']

In [5]:
all_data

{'results/Qwen-7B/checkpoint-500_rosetta2.csv':     match                                           question  sum  mean  \
 0    True  The Fibonacci sequence is a sequence Fn of nat...    4  1.00
 1   False  \nThe Sieve of Eratosthenes is a simple algori...    0  0.00
 2    True  \nSorting Algorithm\nThis is a sorting algorit...    2  0.50
 3   False  A binary search divides a range of values into...    0  0.00
 4    True  Greatest common divisor\nYou are encouraged to...    4  1.00
 5    True  Definitions\nThe factorial of 0 (zero) is defi...    4  1.00
 7   False  A palindrome is a phrase which reads the same ...    0  0.00
 8   False  The prime decomposition of a number is defined...    0  0.00
 9   False  Dijkstra's algorithm, conceived by Dutch compu...    0  0.00
 10   True  \nIn information theory and computer science, ...    1  0.25
 11  False  \nSolve the eight queens puzzle.\nYou can exte...    0  0.00
 15  False  \nSorting Algorithm\nThis is a sorting algorit...    0  0.00
 16  False  Task\nCreate a function that takes a Roman num...    0  0.00
 17  False  \nDefine a subsequence to be any output string...    0  0.00
 19  False  The 24 Game tests one's mental arithmetic.\nTa...    0  0.00

     match_1  match_2  match_3  match_4  \
 0         1        1        1        1
 1         0        0        0        0
 2         0        0        1        1
 3         0        0        0        0
 4         1        1        1        1
 5         1        1        1        1
 7         0        0        0        0
 8         0        0        0        0
 9         0        0        0        0
 10        0        1        0        0
 11        0        0        0        0
 15        0        0        0        0
 16        0        0        0        0
 17        0        0        0        0
 19        0        0        0        0

                                            gen_code_1  \
 0   <reasoning>\nThe task requires generating the ...
 1   <reasoning>\nThe Sieve of Eratosthenes algorit...
 2   <reasoning>\nQuicksort is a divide-and-conquer...
 3   <reasoning>\nBinary search algorithm to find a...
 4   <reasoning>\nThe greatest common divisor (GCD)...
 5   <reasoning>\nThe task requires implementing a ...
 7   <reasoning>\nThe task is to create a Prolog pr...
 8   <reasoning>\nTo solve this problem, we need to...
 9   <reasoning>\nDijkstra's algorithm is a classic...
 10  <reasoning>\nThe Levenshtein distance is a cla...
 11  <reasoning>\nThe eight queens puzzle is a clas...
 15  <reasoning>\nThe merge sort algorithm involves...
 16  <reasoning>\nThe task is to convert a Roman nu...
 17  <reasoning>\nThe problem requires finding the ...
 19  <reasoning>\nThe task requires a Prolog progra...

                                            gen_code_2  \
 0   <reasoning>\nThe task requires generating the ...
 1   <reasoning>\nThe Sieve of Eratosthenes algorit...
 2   <reasoning>\nQuicksort is a divide-and-conquer...
 3   <reasoning>\nBinary search algorithm to find a...
 4   <reasoning>\nThe greatest common divisor (GCD)...
 5   <reasoning>\nThe task requires implementing a ...
 7   <reasoning>\nThe task requires a Prolog progra...
 8   <reasoning>\nTo solve this problem, we need to...
 9   <reasoning>\nDijkstra's algorithm is a classic...
 10  <reasoning>\nThe Levenshtein distance is a wel...
 11  <reasoning>\nThe eight queens puzzle is a clas...
 15  <reasoning>\nThe merge sort algorithm is a cla...
 16  <reasoning>\nThe task requires converting a Ro...
 17  <reasoning>\nThe problem requires finding the ...
 19  <reasoning>\nThe task requires a Prolog progra...

                                            gen_code_3  \
 0   <reasoning>\nThe task requires generating the ...
 1   <reasoning>\nThe Sieve of Eratosthenes algorit...
 2   <reasoning>\nQuicksort is a divide-and-conquer...
 3   <reasoning>\nBinary search algorithm to find a...
 4   <reasoning>\nThe greatest common divisor (GCD)...
 5   <reasoning>\nTo calculate the factorial of a n...
 7   <reasoning>\nThe task requires a Prolog progra...
 8   <reasoning>\nTo solve this problem, we need to...
 9   <reasoning>\nDijkstra's algorithm is a classic...
 10  <reasoning>\nThe Levenshtein distance is a wel...
 11  <reasoning>\nThe eight queens puzzle is a clas...
 15  <reasoning>\nMerge sort is a divide-and-conque...
 16  <reasoning>\nThe task is to convert a Roman nu...
 17  <reasoning>\nThe problem requires finding the ...
 19  <reasoning>\nThe task requires a Prolog progra...

                                            gen_code_4
 0   <reasoning>\nThe task requires generating the ...
 1   <reasoning>\nThe Sieve of Eratosthenes algorit...
 2   <reasoning>\nQuicksort is a divide-and-conquer...
 3   <reasoning>\nBinary search algorithm to find a...
 4   <reasoning>\nThe greatest common divisor (GCD)...
 5   <reasoning>\nThe task requires implementing a ...
 7   <reasoning>\nThe task is to create a Prolog pr...
 8   <reasoning>\nTo solve this problem, we need to...
 9   <reasoning>\nDijkstra's algorithm is a classic...
 10  <reasoning>\nThe Levenshtein distance is a wel...
 11  <reasoning>\nThe eight queens puzzle is a clas...
 15  <reasoning>\nMerge sort is a divide and conque...
 16  <reasoning>\nThe task is to convert a Roman nu...
 17  <reasoning>\nThe problem requires finding the ...
 19  <reasoning>\nThe task requires a Prolog progra...  ,
 'results/Qwen-7B/checkpoint-1000_rosetta2.csv':     match                                           question  sum  mean  \
 0    True  The Fibonacci sequence is a sequence Fn of nat...    4   1.0
 1   False  \nThe Sieve of Eratosthenes is a simple algori...    0   0.0
 2   False  \nSorting Algorithm\nThis is a sorting algorit...    0   0.0
 3   False  A binary search divides a range of values into...    0   0.0
 4    True  Greatest common divisor\nYou are encouraged to...    4   1.0
 5    True  Definitions\nThe factorial of 0 (zero) is defi...    4   1.0
 7   False  A palindrome is a phrase which reads the same ...    0   0.0
 8   False  The prime decomposition of a number is defined...    0   0.0
 9   False  Dijkstra's algorithm, conceived by Dutch compu...    0   0.0
 10  False  \nIn information theory and computer science, ...    0   0.0
 11  False  \nSolve the eight queens puzzle.\nYou can exte...    0   0.0
 15  False  \nSorting Algorithm\nThis is a sorting algorit...    0   0.0
 16  False  Task\nCreate a function that takes a Roman num...    0   0.0
 17  False  \nDefine a subsequence to be any output string...    0   0.0
 19  False  The 24 Game tests one's mental arithmetic.\nTa...    0   0.0

     match_1  match_2  match_3  match_4  \
 0         1        1        1        1
 1         0        0        0        0
 2         0        0        0        0
 3         0        0        0        0
 4         1        1        1        1
 5         1        1        1        1
 7         0        0        0        0
 8         0        0        0        0
 9         0        0        0        0
 10        0        0        0        0
 11        0        0        0        0
 15        0        0        0        0
 16        0        0        0        0
 17        0        0        0        0
 19        0        0        0        0

                                            gen_code_1  \
 0   <reasoning>\nFibonacci sequence\n</reasoning>\...
 1   <reasoning>\nSieve of Eratosthenes\n</reasonin...
 2   <reasoning>\nQuicksort implementation\n</reaso...
 3   <reasoning>\nBinary search implementation\n</r...
 4   <reasoning>\nGCD using Euclid's algorithm\n</r...
 5   <reasoning>\nFactorial calculation\n</reasonin...
 7   <reasoning>\nPalindrome check\n</reasoning>\n<...
 8   <reasoning>\nPrime decomposition\n</reasoning>...
 9   <reasoning>\nDijkstra's algorithm\n</reasoning...
 10  <reasoning>\nLevenshtein distance implementati...
 11  <reasoning>\nSolve the eight queens puzzle\n</...
 15  <reasoning>\nMerge Sort Implementation\n</reas...
 16  <reasoning>\nRoman to decimal conversion\n</re...
 17  <reasoning>\nLCS problem\n</reasoning>\n<code>...
 19  <reasoning>\n24 game solver\n</reasoning>\n<co...

                                            gen_code_2  \
 0   <reasoning>\nFibonacci sequence\n</reasoning>\...
 1   <reasoning>\nSieve of Eratosthenes\n</reasonin...
 2   <reasoning>\nQuicksort implementation\n</reaso...
 3   <reasoning>\nBinary search implementation\n</r...
 4   <reasoning>\nGCD using Euclid's algorithm\n</r...
 5   <reasoning>\nFactorial calculation\n</reasonin...
 7   <reasoning>\nPalindrome check\n</reasoning>\n<...
 8   <reasoning>\nPrime decomposition\n</reasoning>...
 9   <reasoning>\nDijkstra's algorithm\n</reasoning...
 10  <reasoning>\nLevenshtein Distance\n</reasoning...
 11  <reasoning>\nSolve the eight queens puzzle\n</...
 15  <reasoning>\nMerge Sort\n</reasoning>\n<code>\...
 16  <reasoning>\nRoman to decimal conversion\n</re...
 17  <reasoning>\nLCS problem\n</reasoning>\n<code>...
 19  <reasoning>\n24 game solver\n</reasoning>\n<co...

                                            gen_code_3  \
 0   <reasoning>\nFibonacci sequence\n</reasoning>\...
 1   <reasoning>\nSieve of Eratosthenes\n</reasonin...
 2   <reasoning>\nquicksort implementation\n</reaso...
 3   <reasoning>\nBinary search implementation\n</r...
 4   <reasoning>\nGCD using Euclid's algorithm\n</r...
 5   <reasoning>\nFactorial calculation\n</reasonin...
 7   <reasoning>\nPalindrome check\n</reasoning>\n<...
 8   <reasoning>\nPrime decomposition\n</reasoning>...
 9   <reasoning>\nDijkstra's algorithm\n</reasoning...
 10  <reasoning>\nLevenshtein distance implementati...
 11  <reasoning>\nSolve the eight queens puzzle\n</...
 15  <reasoning>\nMerge Sort Algorithm\n</reasoning...
 16  <reasoning>\nRoman to decimal conversion\n</re...
 17  <reasoning>\nLCS problem\n</reasoning>\n<code>...
 19  <reasoning>\n24 game solver\n</reasoning>\n<co...

                                            gen_code_4
 0   <reasoning>\nFibonacci sequence\n</reasoning>\...
 1   <reasoning>\nSieve of Eratosthenes\n</reasonin...
 2   <reasoning>\nQuicksort implementation\n</reaso...
 3   <reasoning>\nBinary search implementation\n</r...
 4   <reasoning>\nGCD using Euclid's algorithm\n</r...
 5   <reasoning>\nFactorial calculation\n</reasonin...
 7   <reasoning>\nPalindrome check\n</reasoning>\n<...
 8   <reasoning>\nPrime decomposition\n</reasoning>...
 9   <reasoning>\nDijkstra's algorithm\n</reasoning...
 10  <reasoning>\nLevenshtein Distance\n</reasoning...
 11  <reasoning>\nSolve the eight queens puzzle\n</...
 15  <reasoning>\nMerge Sort Algorithm\n</reasoning...
 16  <reasoning>\nRoman to decimal conversion\n</re...
 17  <reasoning>\nLCS\n</reasoning>\n<code>\nlcs(X,...
 19  <reasoning>\n24 game solver\n</reasoning>\n<co...  ,
 'results/Qwen-7B/checkpoint-1500_rosetta2.csv':     match                                           question  sum  mean  \
 0    True  The Fibonacci sequence is a sequence Fn of nat...    4  1.00
 1   False  \nThe Sieve of Eratosthenes is a simple algori...    0  0.00
 2    True  \nSorting Algorithm\nThis is a sorting algorit...    1  0.25
 3   False  A binary search divides a range of values into...    0  0.00
 4    True  Greatest common divisor\nYou are encouraged to...    4  1.00
 5    True  Definitions\nThe factorial of 0 (zero) is defi...    2  0.50
 7   False  A palindrome is a phrase which reads the same ...    0  0.00
 8   False  The prime decomposition of a number is defined...    0  0.00
 9   False  Dijkstra's algorithm, conceived by Dutch compu...    0  0.00
 10   True  \nIn information theory and computer science, ...    1  0.25
 11  False  \nSolve the eight queens puzzle.\nYou can exte...    0  0.00
 15  False  \nSorting Algorithm\nThis is a sorting algorit...    0  0.00
 16  False  Task\nCreate a function that takes a Roman num...    0  0.00
 17  False  \nDefine a subsequence to be any output string...    0  0.00
 19  False  The 24 Game tests one's mental arithmetic.\nTa...    0  0.00

     match_1  match_2  match_3  match_4  \
 0         1        1        1        1
 1         0        0        0        0
 2         0        0        1        0
 3         0        0        0        0
 4         1        1        1        1
 5         1        0        0        1
 7         0        0        0        0
 8         0        0        0        0
 9         0        0        0        0
 10        0        1        0        0
 11        0        0        0        0
 15        0        0        0        0
 16        0        0        0        0
 17        0        0        0        0
 19        0        0        0        0

                                            gen_code_1  \
 0   <reasoning>\nFibonacci sequence\n</reasoning>\...
 1   <reasoning>\nSieve of Eratosthenes\n</reasonin...
 2   <reasoning>\nQuicksort implementation\n</reaso...
 3   <reasoning>\nBinary search implementation\n</r...
 4   <reasoning>\nGCD using Euclid's algorithm\n</r...
 5   <reasoning>\nFactorial function\n</reasoning>\...
 7   <reasoning>\nPalindrome checker\n</reasoning>\...
 8   <reasoning>\nPrime decomposition\n</reasoning>...
 9   <reasoning>\nDijkstra's algorithm\n</reasoning...
 10  <reasoning>\nLevenshtein distance implementati...
 11  <reasoning>\nSolve the eight queens puzzle\n</...
 15  <reasoning>\nMerge sort implementation\n</reas...
 16  <reasoning>\nRoman to decimal conversion\n</re...
 17  <reasoning>\nLCS problem\n</reasoning>\n<code>...
 19  <reasoning>\n24 game solver\n</reasoning>\n<co...

                                            gen_code_2  \
 0   <reasoning>\nFibonacci sequence\n</reasoning>\...
 1   <reasoning>\nSieve of Eratosthenes\n</reasonin...
 2   <reasoning>\nQuicksort implementation\n</reaso...
 3   <reasoning>\nBinary search implementation\n</r...
 4   <reasoning>\nGCD using Euclid's algorithm\n</r...
 5   <reasoning>\nFactorial calculation\n</reasonin...
 7   <reasoning>\nPalindrome check\n</reasoning>\n<...
 8   <reasoning>\nPrime decomposition\n</reasoning>...
 9   <reasoning>\nDijkstra's algorithm\n</reasoning...
 10  <reasoning>\nLevenshtein distance implementati...
 11  <reasoning>\nEight Queens Puzzle\n</reasoning>...
 15  <reasoning>\nMerge Sort Algorithm\n</reasoning...
 16  <reasoning>\nRoman to decimal conversion\n</re...
 17  <reasoning>\nLCS problem\n</reasoning>\n<code>...
 19  <reasoning>\n24 game solver\n</reasoning>\n<co...

                                            gen_code_3  \
 0   <reasoning>\nFibonacci sequence\n</reasoning>\...
 1   <reasoning>\nSieve of Eratosthenes\n</reasonin...
 2   <reasoning>\nQuicksort implementation\n</reaso...
 3   <reasoning>\nBinary search implementation\n</r...
 4   <reasoning>\nGCD using Euclid's algorithm\n</r...
 5   <reasoning>\nFactorial calculation\n</reasonin...
 7   <reasoning>\nPalindrome check\n</reasoning>\n<...
 8   <reasoning>\nPrime decomposition\n</reasoning>...
 9   <reasoning>\nDijkstra's algorithm\n</reasoning...
 10  <reasoning>\nLevenshtein distance implementati...
 11  <reasoning>\nEight Queens Puzzle\n</reasoning>...
 15  <reasoning>\nMerge Sort Implementation\n</reas...
 16  <reasoning>\nRoman to decimal conversion\n</re...
 17  <reasoning>\nLCS\n</reasoning>\n<code>\nlcs(X,...
 19  <reasoning>\n24 game solver\n</reasoning>\n<co...

                                            gen_code_4
 0   <reasoning>\nFibonacci sequence\n</reasoning>\...
 1   <reasoning>\nSieve of Eratosthenes\n</reasonin...
 2   <reasoning>\nQuicksort implementation\n</reaso...
 3   <reasoning>\nBinary search implementation\n</r...
 4   <reasoning>\nGCD using Euclid's algorithm\n</r...
 5   <reasoning>\nFactorial calculation\n</reasonin...
 7   <reasoning>\nPalindrome checker\n</reasoning>\...
 8   <reasoning>\nPrime decomposition\n</reasoning>...
 9   <reasoning>\nDijkstra's algorithm\n</reasoning...
 10  <reasoning>\nLevenshtein distance implementati...
 11  <reasoning>\nSolve the eight queens puzzle\n</...
 15  <reasoning>\nMerge sort implementation\n</reas...
 16  <reasoning>\nRoman to decimal conversion\n</re...
 17  <reasoning>\nLCS problem\n</reasoning>\n<code>...
 19  <reasoning>\n24 game solver\n</reasoning>\n<co...  ,
 'results/Qwen-3B/checkpoint-500_rosetta2.csv':     match                                           question  sum  mean  \
 0    True  The Fibonacci sequence is a sequence Fn of nat...    1  0.25
 1   False  \nThe Sieve of Eratosthenes is a simple algori...    0  0.00
 2    True  \nSorting Algorithm\nThis is a sorting algorit...    4  1.00
 3   False  A binary search divides a range of values into...    0  0.00
 4   False  Greatest common divisor\nYou are encouraged to...    0  0.00
 5    True  Definitions\nThe factorial of 0 (zero) is defi...    4  1.00
 7   False  A palindrome is a phrase which reads the same ...    0  0.00
 8   False  The prime decomposition of a number is defined...    0  0.00
 9   False  Dijkstra's algorithm, conceived by Dutch compu...    0  0.00
 10  False  \nIn information theory and computer science, ...    0  0.00
 11  False  \nSolve the eight queens puzzle.\nYou can exte...    0  0.00
 15  False  \nSorting Algorithm\nThis is a sorting algorit...    0  0.00
 16  False  Task\nCreate a function that takes a Roman num...    0  0.00
 17  False  \nDefine a subsequence to be any output string...    0  0.00
 19  False  The 24 Game tests one's mental arithmetic.\nTa...    0  0.00

     match_1  match_2  match_3  match_4  \
 0         1        0        0        0
 1         0        0        0        0
 2         1        1        1        1
 3         0        0        0        0
 4         0        0        0        0
 5         1        1        1        1
 7         0        0        0        0
 8         0        0        0        0
 9         0        0        0        0
 10        0        0        0        0
 11        0        0        0        0
 15        0        0        0        0
 16        0        0        0        0
 17        0        0        0        0
 19        0        0        0        0

                                            gen_code_1  \
 0   <reasoning>\nThe task is to generate the nth F...
 1   <reasoning>\nThe Sieve of Eratosthenes is an a...
 2   <reasoning>\nThe task is to implement the Quic...
 3   <reasoning>\nThe task is to implement a binary...
 4   <reasoning>\nTo find the greatest common divis...
 5   <reasoning>\nThe task is to implement a functi...
 7   <reasoning>\nTo determine if a given sequence ...
 8   <reasoning>\nTo solve this problem, we need to...
 9   <reasoning>\nThe task is to implement Dijkstra...
 10  <reasoning>\nThe task is to implement a functi...
 11  <reasoning>\nThe eight queens puzzle is a clas...
 15  <reasoning>\nThe task is to implement the merg...
 16  <reasoning>\nTo create a function that convert...
 17  <reasoning>\nThe problem requires finding the ...
 19  <reasoning>\nThe task requires generating four...

                                            gen_code_2  \
 0   <reasoning>\nThe task is to generate the nth F...
 1   <reasoning>\nThe Sieve of Eratosthenes is an a...
 2   <reasoning>\nThe task is to implement the Quic...
 3   <reasoning>\nThe task is to implement a binary...
 4   <reasoning>\nTo find the greatest common divis...
 5   <reasoning>\nThe task is to implement a functi...
 7   <reasoning>\nTo determine if a given sequence ...
 8   <reasoning>\nThe task is to find the prime dec...
 9   <reasoning>\nThe task is to implement Dijkstra...
 10  <reasoning>\nThe task is to implement a functi...
 11  <reasoning>\nThe eight queens puzzle is a clas...
 15  <reasoning>\nThe task is to implement the merg...
 16  <reasoning>\nTo create a function that convert...
 17  <reasoning>\nThe problem requires finding the ...
 19  <reasoning>\nThe task requires generating four...

                                            gen_code_3  \
 0   <reasoning>\nThe task is to generate the nth F...
 1   <reasoning>\nThe Sieve of Eratosthenes is an a...

In [6]:
df = pd.DataFrame({
    "name": all_data.keys(),
    "accuracy": [all_data[key]["match"].sum()/len(all_data[key]) for key in all_data.keys()],
    "strict_accuracy": [(all_data[key]["sum"] == 4).sum()/len(all_data[key]) for key in all_data.keys()]
})
display(df)

,name,accuracy,strict_accuracy
0,results/Qwen-7B/checkpoint-500_rosetta2.csv,0.333333,0.200000
1,results/Qwen-7B/checkpoint-1000_rosetta2.csv,0.200000,0.200000
2,results/Qwen-7B/checkpoint-1500_rosetta2.csv,0.333333,0.133333
3,results/Qwen-3B/checkpoint-500_rosetta2.csv,0.200000,0.133333
4,results/Qwen-3B/checkpoint-1000_rosetta2.csv,0.200000,0.000000
5,results/Qwen-3B/checkpoint-1500_rosetta2.csv,0.133333,0.066667
6,results/Qwen-1.5B_one_shot/checkpoint-500_rose...,0.000000,0.000000
7,results/Qwen-1.5B_one_shot/checkpoint-1000_ros...,0.066667,0.000000
8,results/Qwen-1.5B_one_shot/checkpoint-1500_ros...,0.066667,0.000000
9,results/Base/zero_shot/0.5_rosetta2.csv,0.000000,0.000000
10,results/Base/zero_shot/7_rosetta2.csv,0.200000,0.200000
11,results/Base/zero_shot/3_rosetta2.csv,0.133333,0.000000
12,results/Base/zero_shot/1.5_rosetta2.csv,0.000000,0.000000
13,results/Base/one_shot/0.5_rosetta2.csv,0.000000,0.000000
14,results/Base/one_shot/7_rosetta2.csv,0.266667,0.200000
15,results/Base/one_shot/3_rosetta2.csv,0.066667,0.000000
16,results/Base/one_shot/1.5_rosetta2.csv,0.000000,0.000000
17,results/Base/five_shot/0.5_rosetta2.csv,0.000000,0.000000
18,results/Base/five_shot/7_rosetta2.csv,0.333333,0.266667
19,results/Base/five_shot/3_rosetta2.csv,0.066667,0.000000
20,results/Base/five_shot/1.5_rosetta2.csv,0.066667,0.000000
21,results/Qwen-7B_five_shot/checkpoint-500_roset...,0.333333,0.133333
22,results/Qwen-7B_five_shot/checkpoint-1000_rose...,0.266667,0.200000
23,results/Qwen-7B_five_shot/checkpoint-1500_rose...,0.266667,0.200000
24,results/Qwen-1.5B/checkpoint-500_rosetta2.csv,0.066667,0.066667
25,results/Qwen-1.5B/checkpoint-1000_rosetta2.csv,0.133333,0.066667
26,results/Qwen-1.5B/checkpoint-1500_rosetta2.csv,0.133333,0.000000
27,results/Qwen-7B_one_shot/checkpoint-500_rosett...,0.333333,0.266667
28,results/Qwen-7B_one_shot/checkpoint-1000_roset...,0.200000,0.200000
29,results/Qwen-7B_one_shot/checkpoint-1500_roset...,0.266667,0.200000
30,results/Qwen-3B_one_shot/checkpoint-500_rosett...,0.133333,0.066667
31,results/Qwen-3B_one_shot/checkpoint-1000_roset...,0.133333,0.066667
32,results/Qwen-3B_one_shot/checkpoint-1500_roset...,0.133333,0.066667
33,results/Qwen-0.5B/checkpoint-500_rosetta2.csv,0.000000,0.000000
34,results/Qwen-0.5B/checkpoint-1000_rosetta2.csv,0.000000,0.000000
35,results/Qwen-0.5B/checkpoint-1500_rosetta2.csv,0.000000,0.000000
36,results/Qwen-0.5B_one_shot/checkpoint-500_rose...,0.000000,0.000000
37,results/Qwen-0.5B_one_shot/checkpoint-1000_ros...,0.000000,0.000000
38,results/Qwen-0.5B_one_shot/checkpoint-1500_ros...,0.000000,0.000000